version: "3.9"

services:
  db:
    image: postgres:16
    container_name: snowbank_db
    profiles: ["dev"]
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: snow_bank_development
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    container_name: snowbank_db_test
    profiles: ["test"]
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: snow_bank_test
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: snowbank_redis
    profiles: ["dev"]
    ports:
      - "6379:6379"

  search:
    image: opensearchproject/opensearch:2.13.0
    container_name: snowbank_search
    profiles: ["dev"]
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 3s
      retries: 30

volumes:
  dbdata: {}
