version: "3.9"

services:
  web:
    image: ghcr.io/tu_org/snow_bank_api:prod-latest
    profiles: ["prod"]
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_MAX_THREADS: "5"
      PORT: "80"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL:-}
      SEARCH_URL: ${SEARCH_URL:-}
      CORS_ORIGINS: ${CORS_ORIGINS:-https://tu-dominio.com}
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:80/up"]
      interval: 10s
      timeout: 3s
      retries: 30
